<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <script src="../jQuery-3.x-1.x/jquery-3.2.1.min.js"></script>
</head>
<body>
    <h3>1.严格模式，“use strict"</h3>
    <p>非严格模式下，忘记将let放在变量之前，默认是生成一个全局变量，而严格模式下则会抛出错误。</p>
    <script>
    "use strict"
        let count=10;
        console.log(count)
    </script>

    <p>在非严格模式下，this是全局范围作用域，this的属性是全局属性，如果没有用new关键字调用构造函数，则函数内的this不会指向该对象，而仍然是全局变量，如果使用new关键字调用构造函数，则生成了一个新的对象，函数内的this指向person对象。</p>
    <script>       
        function person(name){
            this.name=name;
            console.log(this.name,this)
        }
        let lihua= person("lihua");
        console.log(name)
        let liming = new person("liming")
        console.log(name)
    </script>
    <p>严格模式下，如不使用new关键字调用函数，则会抛出错误，函数内部的this是undefined，如果使用new关键字调用函数，则生成一个对象，函数内的this指向该对象。</p>
    <script>
        "use strict"
        console.log("this",this)
        function person2(name){
            console.log("person",this)
            if(this) {this.name=name;
            console.log(this.name,name)}
        }
 //       debugger;
        person2();
        let xiaoming = new person2("xiaoming");
        console.log("name",name);
        let xiaohong = person2("xiaohong")
    </script>
    <h3>调试</h3>
    <ul>
        <li>使用console.log()在控制台查看输出</li>
        <li>使用浏览器的调试器的功能</li>
        <li>在程序中插入debugger;语句，相当于设置断点。</li>
    </ul>
    <h3>异常</h3>
    <ul>
        <li>当一个函数无法继续执行下去时，停止正在做的事情而跳转到一个知道如何处理问题额地方，这个是异常处理</li>
        <li><span style="font-size:1.2rem; color: #56ee56;">栈展开：</span>遇到问题的代码可以引发异常，从而使函数从超远距离返回，不仅跳出当前函数及其调用者，一直调到最开始执行的调用，是函数调用栈的逆过程，异常时收缩此栈，并删除上下文。</li>
        <li>捕获异常： 在栈中设置障碍物，栈收缩时捕获异常。
            <ul>
                <li>throw关键字用于引发异常</li>
                <li>try{...}catch(error){...} 这两个块用来处理异常</li>
                <li>异常处理代码只在引发异常和处理异常的地方执行，中间函数不会发现也不会处理。</li>

            </ul>
        </li>
        <li>异常清理： try语句后还可以跟finally块，表示无论发生什么，在运行try块中的代码后都运行finally块中的代码</li>
    </ul>
    <script>
        console.log("异常测试")
        function direction(question){
            console.log(question);
            let result = prompt(question);
            console.log(result);
            if(result.toLowerCase()=="left") return "L";
            if(result.toLowerCase()=="right") return "R";
            throw new Error("Invalid direction " + result)
        }
        function look(){
            if(direction("which way? ") == "L"){
                return "a house";
            }
            else{
                return "tow angry beers"
            }
        }
        try{
            console.log("你在往哪看呢？")
            console.log("you see",look());
        }catch(error){
            console.log("error是什么？ ",error);
            console.log("something went wrong: " + error);
            console.log("error 就是发生异常时返回的Error对象，Error对象记录了引发异常的调用栈的信息，告诉我们发生异常的位置和函数，用作栈追踪的作用。")
        }
    </script>

    <h3>对于程序员的错误，让错误通过是能做的最好的事，而不是让未处理的异常来使程序崩溃。</h3>
    <h3>选择性捕获</h3>
    <ul>
        <li>当进入catch体时，一定是try体中出现了异常，但我们不知道是哪个引起了异常</li>
        <li>JS 不提供选择性捕获，要么全部捕获，要么不捕获，而写在catch块中的处理异常的情况不一定适合捕获的异常，如上一个问路程序并不是输入错误而是引用方法时拼写错误，这个异常并不能在catch中有对应的处理</li>
        <li>一般情况下，不要想着在catch块里处理所有的异常，而是捕获并处理特定的异常，对于其他的，则可以重新抛出新的异常</li>
        <li>在catch块中选择捕获InputError异常，放行其他的异常，如果再引入拼写错误之类，则会正确报告未定义的异常</li>
    </ul>
    <script>
        class InputError extends Error{};  
        function direction2(question){
            let result= prompt(question);
            if(result.toLowerCase()=="left") return "L";
            if(result.toLowerCase()=="right") return "R";
            throw new InputError("Invalid direction " + result)
        }
        for(; ;){
            try{
                let dir = direction("where? " );
                console.log("you choose ",dir);
                break;
            }catch(e){
                if(e instanceof InputError){
                    console.log("Invalid direction try again")
                }else{
                    throw e;
                }
            }
        }
    </script>
    <form>
        <input id="x">+<input id="y">
        <button id="add" type="button">计算</button>
    </form>
    <script>
        'use strict';
        var $btn=$('#add');
        $btn.off('click');
       
            $btn.click(function(){
                try{
            var x=parseFloat($('#x').val()),
                y=parseFloat($('#y').val()),
                r;
            if(isNaN(x)||isNaN(y)){
                throw new Error('输入错误')
            }
            r=x+y;
            alert('计算结果：'+r);
            }catch(e){
            alert('输入错误')
        }}
        );
        
    </script>
    
</body>
</html>